### ISSUE TITLE
Pro tip: gebruik pseudo-private customproperties voor DRY code

### ISSUE THREAD

**Issue by joostf** [DivaniNL/look-and-feel-styleguide#30]
Overweeg met je team of je gebruik wil maken van pseudo-private custom properties om je code DRY te maken en daarmee overzichtelijker (opinionated). Zo ja, voeg het toe aan jullie conventies.

Dit concept is bedacht door Lea Verou: https://lea.verou.me/blog/2021/10/custom-properties-with-defaults/

Code voor buttons en variaties op buttons ziet er dan bijvoorbeeld zo uit. 
Zoals je ziet hoeven voor variaties alleen nog maar de 'private' properties aangepast te worden

```css
button {
            --_gap: 0.5em;
            --_padding-block: 0.75em;
            --_padding-inline: 1.5em;
            --_border-width: 0.0625rem;
            --_border-color: var(--color-border);
            --_radius: 0.5rem;
            --_bg: var(--color-surface);
            --_color: var(--color-text);
            --_font-weight: 500;
            --_transition-duration: 0.2s;
            --_transition-timing: cubic-bezier(0.4, 0, 0.2, 1);
            
            display: inline-flex;
            align-items: center;
            justify-content: center;
            gap: var(--_gap);
            padding: var(--_padding-block) var(--_padding-inline);
            border: var(--_border-width) solid var(--_border-color);
            border-radius: var(--_radius);
            background-color: var(--_bg);
            color: var(--_color);
            font-weight: var(--_font-weight);
            cursor: pointer;
            transition: all var(--_transition-duration) var(--_transition-timing);

            &:hover:not(:disabled) {
                --_border-color: var(--color-accent);
                --_color: var(--color-accent);
                --_transform: translateY(-0.125rem);
                transform: var(--_transform);
            }

            &:active:not(:disabled) {
                --_border-color: color-mix(in srgb, var(--color-accent) 80%, black);
                --_color: color-mix(in srgb, var(--color-accent) 80%, black);
                --_transform: translateY(0.0625rem);
                transform: var(--_transform);
            }

            &.btn-primary {
                --_bg: var(--color-primary);
                --_color: white;
                --_border-color: transparent;
                
                &:hover:not(:disabled) {
                    --_bg: var(--color-accent);
                    --_color: white;
                }

                &:active:not(:disabled) {
                    --_bg: color-mix(in srgb, var(--color-accent) 80%, black);
                    --_color: white;
                }
            }
...
```
